import {
  benefitsTypeSchema,
  diversityTypeSchema,
  experienceTypeSchema,
  jobStatusSchema,
  jobTypeSchema,
  passoutYearSchema,
  stipendTypeSchema,
  workplaceTypeSchema,
} from "@/constants/jobOpportunities";
import { string, z } from "zod";

export const opportunitySchema = z.object({
  companyId: z.string(),
  title: z.string(),
  description: z.string(),
  location: z.string().array(),
  duration: z.string().optional(),
  type: jobTypeSchema,
  workplaceType: workplaceTypeSchema,
  stipendType: stipendTypeSchema,
  diversityType: diversityTypeSchema.optional(),
  experience: experienceTypeSchema,
  yearsOfExperience: z.string().default("0"),
  degree: string().array().optional(),
  benefits: benefitsTypeSchema.array().optional(),
  salary: z.string().optional(),
  status: jobStatusSchema.default("active"),
  jobLink: z.string(),
  passoutYear: passoutYearSchema.array().optional(),
  category: z.string().array().optional(),
  deadline: z.string().date(),
  postedAt: z.string().date(),
  referrals: z.string().array().optional(),
  // skilsrequired: z.string(),
});
